// ignore_for_file: file_names
const Map<String, String> arEG = {
  // General
  'app_title': 'مرشد',
  'app_name': 'مُرشد',
  'login': 'تسجيل الدخول',
  'logout': 'تسجيل الخروج',
  'home': 'الرئيسية',
  'settings': 'الإعدادات',
  'welcome': 'أهلاً وسهلاً',
  'success': 'نجاح',
  'warning': 'تحذير',
  'error': 'خطأ',
  'send': 'إرسال',
  'from': 'من',

  // Login Screen
  'welcome_to_murshid': 'مرحباً بك في مرشد',
  'smart_university_assistant': 'مساعد ذكي للجامعة',
  'login_title': 'تسجيل الدخول',
  'enter_credentials': 'الرجاء إدخال بيانات دخولك',
  'email': 'البريد الإلكتروني',
  'email_hint': 'example@murshid.com',
  'password': 'كلمة المرور',
  'password_hint': '••••••••',
  'please_enter_email': 'الرجاء إدخال البريد الإلكتروني',
  'please_enter_valid_email': 'الرجاء إدخال بريد إلكتروني صحيح',
  'please_enter_password': 'الرجاء إدخال كلمة المرور',
  'password_min_length': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
  'please_fill_all_fields': 'الرجاء ملء جميع الحقول',
  'no_account': 'ليس لديك حساب؟ ',
  'register_now': 'سجل الآن',

  // Signup Screen
  'create_new_account': 'إنشاء حساب جديد',
  'join_murshid': 'انضم إلى مرشد - مساعد ذكي للجامعة',
  'full_name': 'الاسم الكامل',
  'enter_full_name': 'أدخل اسمك الكامل',
  'please_enter_full_name': 'الرجاء إدخال اسمك الكامل',
  'university_id': 'رقم البطاقة الجامعية',
  'enter_university_id': 'أدخل رقم بطاقتك',
  'please_enter_university_id': 'الرجاء إدخال رقم البطاقة الجامعية',
  'please_enter_valid_email_short': 'الرجاء إدخال بريد صحيح',
  'email_verification_hint': 'سيتم إرسال رابط تحقق إلى بريدك الإلكتروني',
  'choose_account_type': 'اختر نوع الحساب:',
  'student': 'طالب',
  'professor': 'محاضر',
  'create_account': 'إنشاء حساب',
  'already_have_account': 'لديك حساب بالفعل؟ ',
  'invalid_id': 'رقم بطاقة غير صحيح',
  'id_not_matching': 'رقم البطاقة لا يطابق سجلات المحاضرين لدينا',
  'account_created_success': 'تم إنشاء الحساب بنجاح',

  // Student Home Screen
  'academic_portal': 'البوابة الأكاديمية',
  'welcome_greeting': 'مرحباً بك',
  'default_student': 'طالب',
  'upcoming_lecture': 'المحاضرة القادمة',
  'time_label': 'الوقت',
  'location_label': 'المكان',
  'start_guidance': 'بدء الإرشاد',
  'today': 'اليوم',
  'view_all': 'عرض الكل',
  'no_lectures_today': 'لا توجد محاضرات مسجلة اليوم',
  'no_connection': 'بدون إتصال',
  'no_internet_message': 'لا يوجد اتصال بالإنترنت. يرجى التحقق من الاتصال.',
  'no_internet_banner': 'بدون اتصال بالإنترنت',
  'connected': 'متصل',
  'connection_restored': 'تم استرجاع الاتصال بالإنترنت',

  // Professor Home Screen
  'faculty_portal': 'بوابة أعضاء هيئة التدريس',
  'alert_students': 'تنبيه الطلاب',
  'send_quick_alert': 'إرسال تنبيه سريع',
  'alert_title': 'العنوان',
  'alert_message': 'رسالة التنبيه',
  'alert_prefix': 'تنبيه:',

  // Full Schedule Screen
  'full_schedule': 'الجدول الدراسي الكامل',
  'day_saturday': 'السبت',
  'day_sunday': 'الأحد',
  'day_monday': 'الاثنين',
  'day_tuesday': 'الثلاثاء',
  'day_wednesday': 'الأربعاء',
  'day_thursday': 'الخميس',
  'no_lectures_on_day': 'لا توجد محاضرات في هذا اليوم',
  'hall_label': 'قاعة:',
  'note_sent_successfully': 'تم إرسال الملاحظة بنجاح',

  // Notification Screen
  'notification_center': 'مركز التنبيهات',
  'no_notifications': 'لا توجد تنبيهات',
  'no_notifications_message': 'لم تتلقَ أي تنبيهات حتى الآن',
  'important_update': 'تحديث مهم',
  'department': 'القسم',

  // Add Course Screen
  'add_new_lecture': 'إضافة محاضرة جديدة',
  'course_details': 'تفاصيل المقرر',
  'course_code': 'رمز المقرر',
  'course_name': 'اسم المقرر',
  'enter_course_code': 'أدخل رمز المقرر',
  'enter_course_name': 'أدخل اسم المقرر',
  'room_and_time': 'القاعة والوقت',
  'select_room': 'اختر القاعة',
  'select_day': 'اختر اليوم',
  'start_time': 'وقت البداية',
  'end_time': 'وقت النهاية',
  'add_students': 'إضافة الطلاب',
  'selected_students_count': 'عدد الطلاب المختارين:',
  'fill_all_fields': 'يجب ملء جميع الحقول',
  'select_at_least_one_student': 'يجب اختيار طالب واحد على الأقل',
  'course_created_success': 'تم إنشاء المحاضرة بنجاح',
  'course_creation_failed': 'فشل إنشاء المقرر',
  'schedule_creation_failed': 'فشل إنشاء الجدول',
  'error_occurred': 'حدث خطأ:',

  // Course Selection Screen
  'select_courses': 'اختر المقررات',
  'select_courses_to_teach': 'اختر المقررات للتدريس',
  'no_courses_available': 'لا توجد مقررات متاحة',
  'confirm_selection': 'تأكيد الاختيار',
  'selection_saved': 'تم حفظ اختيارك بنجاح',
  'selection_failed': 'فشل حفظ الاختيار:',
};
