// ignore_for_file: file_names
const Map<String, String> enUS = {
  // General
  'app_title': 'Murshid',
  'app_name': 'Murshid',
  'login': 'Login',
  'logout': 'Logout',
  'home': 'Home',
  'settings': 'Settings',
  'welcome': 'Welcome',
  'success': 'Success',
  'warning': 'Warning',
  'error': 'Error',
  'send': 'Send',
  'from': 'From',

  // Login Screen
  'welcome_to_murshid': 'Welcome to Murshid',
  'smart_university_assistant': 'Smart University Assistant',
  'login_title': 'Login',
  'enter_credentials': 'Please enter your credentials',
  'email': 'Email',
  'email_hint': 'example@murshid.com',
  'password': 'Password',
  'password_hint': '••••••••',
  'please_enter_email': 'Please enter your email',
  'please_enter_valid_email': 'Please enter a valid email',
  'please_enter_password': 'Please enter your password',
  'password_min_length': 'Password must be at least 6 characters',
  'please_fill_all_fields': 'Please fill all fields',
  'no_account': "Don't have an account? ",
  'register_now': 'Register Now',

  // Signup Screen
  'create_new_account': 'Create New Account',
  'join_murshid': 'Join Murshid - Smart University Assistant',
  'full_name': 'Full Name',
  'enter_full_name': 'Enter your full name',
  'please_enter_full_name': 'Please enter your full name',
  'university_id': 'University ID',
  'enter_university_id': 'Enter your university ID',
  'please_enter_university_id': 'Please enter your university ID',
  'please_enter_valid_email_short': 'Please enter a valid email',
  'email_verification_hint': 'A verification link will be sent to your email',
  'choose_account_type': 'Choose account type:',
  'student': 'Student',
  'professor': 'Professor',
  'create_account': 'Create Account',
  'already_have_account': 'Already have an account? ',
  'invalid_id': 'Invalid ID',
  'id_not_matching': 'ID does not match our professor records',
  'account_created_success': 'Account created successfully',

  // Student Home Screen
  'academic_portal': 'ACADEMIC PORTAL',
  'welcome_greeting': 'Welcome',
  'default_student': 'Student',
  'upcoming_lecture': 'Upcoming Lecture',
  'time_label': 'Time',
  'location_label': 'Location',
  'start_guidance': 'Start Guidance',
  'today': 'Today',
  'view_all': 'View All',
  'no_lectures_today': 'No lectures scheduled for today',
  'no_connection': 'No Connection',
  'no_internet_message':
      'No internet connection. Please check your connection.',
  'no_internet_banner': 'No internet connection',
  'connected': 'Connected',
  'connection_restored': 'Internet connection restored',

  // Professor Home Screen
  'faculty_portal': 'Faculty Portal',
  'alert_students': 'Alert Students',
  'send_quick_alert': 'Send Quick Alert',
  'alert_title': 'Title',
  'alert_message': 'Alert Message',
  'alert_prefix': 'Alert:',

  // Full Schedule Screen
  'full_schedule': 'Full Schedule',
  'day_saturday': 'Saturday',
  'day_sunday': 'Sunday',
  'day_monday': 'Monday',
  'day_tuesday': 'Tuesday',
  'day_wednesday': 'Wednesday',
  'day_thursday': 'Thursday',
  'no_lectures_on_day': 'No lectures on this day',
  'hall_label': 'Hall:',
  'note_sent_successfully': 'Note sent successfully',

  // Notification Screen
  'notification_center': 'Notification Center',
  'no_notifications': 'No Notifications',
  'no_notifications_message': 'You have not received any notifications yet',
  'important_update': 'Important Update',
  'department': 'Department',

  // Add Course Screen
  'add_new_lecture': 'Add New Lecture',
  'course_details': 'Course Details',
  'course_code': 'Course Code',
  'course_name': 'Course Name',
  'enter_course_code': 'Enter course code',
  'enter_course_name': 'Enter course name',
  'room_and_time': 'Room & Time',
  'select_room': 'Select Room',
  'select_day': 'Select Day',
  'start_time': 'Start Time',
  'end_time': 'End Time',
  'add_students': 'Add Students',
  'selected_students_count': 'Selected students:',
  'fill_all_fields': 'All fields must be filled',
  'select_at_least_one_student': 'You must select at least one student',
  'course_created_success': 'Lecture created successfully',
  'course_creation_failed': 'Failed to create course',
  'schedule_creation_failed': 'Failed to create schedule',
  'error_occurred': 'An error occurred:',

  // Course Selection Screen
  'select_courses': 'Select Courses',
  'select_courses_to_teach': 'Select Courses to Teach',
  'no_courses_available': 'No courses available',
  'confirm_selection': 'Confirm Selection',
  'selection_saved': 'Your selection has been saved successfully',
  'selection_failed': 'Failed to save selection:',
};
